---

- name: install k8s repo
  yum_repository:
    name: kubernetes
    description: Kubernetes YUM repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: no
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude: kubelet kubeadm kubectl

- name: set Selinux disabled
  selinux: 
    state: disabled

- name: install kubelet
  yum:
    name:
      - kubelet-1.24.1
      - kubeadm-1.24.1
    state: present
    disable_excludes: kubernetes

- name: remove swap from fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: remove swap for current session
  command: swapoff -a

- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: add hosts file
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"

- name: install bridge-utils
  yum:
    name: bridge-utils
    state: present

- name: modprobe br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: create autoload file for br_netfilter module
  copy:
    content: br_netfilter
    dest: /etc/modules-load.d/br_netfilter.conf

- name: add sysctl ip_forward=1
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present

- name: add sysctl bridge-nf-call-iptables=1
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present

- name: install cri-o repo
  yum_repository:
    name: cri-o
    description: Cri-o yum repository
    baseurl: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/repodata/repomd.xml.key


- name: install cri-o repo v1.24.3
  yum_repository:
    name: cri-o-v1-24
    description: Cri-o v1.24.3 yum repository
    baseurl: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24:/1.24.3/CentOS_7/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24:/1.24.3/CentOS_7/repodata/repomd.xml.key

- name: install cri-o
  yum:
    name: cri-o
    state: present 

- name: start cri-o
  systemd:
    name: crio
    state: started
    enabled: true

- name: enable kubelet
  systemd:
    name: kubelet
    enabled: true

- name: remove cni bridge for calico or flannel support
  file:
    path: /etc/cni/net.d/100-crio-bridge.conf
    state: absent

- name: predownload kube-flannel image for faster node initialization
  command: crictl pull docker.io/rancher/mirrored-flannelcni-flannel:v0.20.1

- name: predownload kube-flannel cni-plugin image for faster node initialization
  command: crictl pull docker.io/rancher/mirrored-flannelcni-flannel-cni-plugin:v1.1.0
