stages:
  - build
  - test
  - package

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "-----BEGIN CERTIFICATE-----
      MIIDxDCCAqygAwIBAgIJAPwwufRg/C0hMA0GCSqGSIb3DQEBCwUAMIGKMQswCQYD
      VQQGEwJSVTELMAkGA1UECAwCU1QxGzAZBgNVBAoMEkxvY2FsIERldmVsb3BlbWVu
      dDEbMBkGA1UEBwwSTG9jYWwgRGV2ZWxvcGVtZW50MRcwFQYDVQQDDA4qLmthcmVl
      bS5sb2NhbDEbMBkGA1UECwwSTG9jYWwgRGV2ZWxvcGVtZW50MB4XDTIyMTAxOTEy
      MDQyNVoXDTMyMTAxNjEyMDQyNVowgYoxCzAJBgNVBAYTAlJVMQswCQYDVQQIDAJT
      VDEbMBkGA1UECgwSTG9jYWwgRGV2ZWxvcGVtZW50MRswGQYDVQQHDBJMb2NhbCBE
      ZXZlbG9wZW1lbnQxFzAVBgNVBAMMDioua2FyZWVtLmxvY2FsMRswGQYDVQQLDBJM
      b2NhbCBEZXZlbG9wZW1lbnQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
      AQCxIOVLZZ4VJ/9xFCjNvBOellw+B1CAbuCDZW+6ot4mI8DWdzTagGOdoJtFe645
      t/UE/0+IHOlf5s1tbPK02tZ+F6crd3/EKRWFf2aCkh0ge2sRWZmSZyJD4nITRik/
      bfmZJ3789W9DX9NoGW5FjCPiQr43+NR+0ITehkcbV7roHo8jLxVTKMMvaHIPn0xC
      hXfP2jRuXfh5M7iVJWTNggOLWDVMkDs9e+wb/UF5pxR7uM7ZIA8nqpQSD5KQ1pt2
      uWrhL9fKJmCLf7eZZ++Lku/oBnDm7y9TmOdZ9Rssj39BgGzrmpVgkY97naYC5l4H
      nlLmAB4x+Ar5i2uOGywElTOhAgMBAAGjKzApMCcGA1UdEQQgMB6CDGthcmVlbS5s
      b2NhbIIOKi5rYXJlZW0ubG9jYWwwDQYJKoZIhvcNAQELBQADggEBAC+oT/DObqUq
      pWm44oreSB/Y8DHibfaDJ/DgcHc/SjtR6k6BNAg8hQf85TdFEXfrY8YsYUCt0/QH
      he07Yv+3zhp1/v6Vs/iLVmykdZkJp5YrFBoNDNGG7HSfEBCEiSixk+8GF61FI0xU
      jd0ZylRiee5hetjoJ8DmbfdjZrXRHxyA2MiBZHeem+pAlLrAE6yra443oG5sDzRO
      1k5aUx8eGTbprQ67/M4sb2jN8i0JcXkgpO9oJlT14E0znO7PzzL/JcRxZFfoEaDW
      UrYHvJV9LB/wwRqIqqqPE9e/MVbBEpqsFY+yfomQgz0jYGJwNpgqAASeotZ+LjTg
      n94Mzuc4RhU=
      -----END CERTIFICATE-----" >> /kaniko/ssl/certs/additional-ca-cert-bundle.crt
  script:
    - /kaniko/executor 
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}"
      --skip-tls-verify

