---
apiVersion: v1
kind: Namespace
metadata:
  name: proxmox-autoscaler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxmox-autoscaler
  namespace: proxmox-autoscaler
spec:
  selector:
    matchLabels:
      app: proxmox-autoscaler
  template:
    metadata:
      labels:
        app: proxmox-autoscaler
    spec:
      initContainers:
      - name: init-kubeadm
        image: registry.example.local/proxmox-autoscaler/k8s-proxmox-autoscaler:main
        command: ["bash", "-c", "cp /hostbin/kubeadm /kubeadm && cp -r /kube-config/* /etc/kubernetes"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        volumeMounts:
        - name: init-hostbin
          mountPath: "/hostbin"
        - name: init-kubeadm-config
          mountPath: "/kube-config"
        - name: kubeadm
          mountPath: "/kubeadm"
        - name: kubeadm-config
          mountPath: "/etc/kubernetes"
      containers:
      - name: proxmox-autoscaler
        image: registry.example.local/proxmox-autoscaler/k8s-proxmox-autoscaler:main
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        volumeMounts:
        - name: kubeadm
          mountPath: "/usr/local/sbin"
        - name: kubeadm-config
          mountPath: "/etc/kubernetes"
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
      volumes:
        - name: init-hostbin
          hostPath:
            path: "/usr/bin"
        - name: kubeadm
          emptyDir: {}
        - name: init-kubeadm-config
          hostPath:
            path: "/etc/kubernetes"
        - name: kubeadm-config
          emptyDir: {}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: proxmox-autoscaler
rules:
- apiGroups: [""]
  resources:
    - nodes
  verbs:
    - get
    - list
    - patch
    - delete
- apiGroups: [""]
  resources:
    - pods
    - nodes/status
  verbs:
    - get
    - list
- apiGroups: ["metrics.k8s.io"]
  resources:
    - nodes
    - pods
  verbs:
    - get
    - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: proxmox-autoscaler
subjects:
- kind: ServiceAccount
  name: default
  namespace: proxmox-autoscaler
roleRef:
  kind: ClusterRole
  name: proxmox-autoscaler
  apiGroup: rbac.authorization.k8s.io